CREATE DATABASE db_hogares;
GO
USE db_hogares
GO

CREATE TABLE Casas (
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Nombre] NVARCHAR(100) NOT NULL,
	[Direccion] NVARCHAR(250) NOT NULL,
	[Telefono] NVARCHAR(10) NOT NULL,
	[Fecha] SMALLDATETIME NOT NULL,
	[Activa] BIT NOT NULL,
);